#!/bin/bash

echo "Current Dir: $(pwd)"
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"
echo "COMMIT_MSG: ${COMMIT_MSG}"
echo "DOCKER_REPO: ${DOCKER_REPO}"
echo "DOCKERFILE_PATH: ${DOCKERFILE_PATH}"
echo "DOCKER_TAG: ${DOCKER_TAG}"
echo "IMAGE_NAME: ${IMAGE_NAME}"

if [[ -z "${MINVER_IMAGE}" ]]; then
  docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
else
  docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME --build-arg MINVER_IMAGE=$MINVER_IMAGE .
fi
