name: Build minver-cli image

on:
  push:
    branches: ["main", "dev*"]
    tags: ["minver-*.*.*", "minver-*.*"]
  pull_request:
    branches: [main]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    name: build-${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3

      - name: Docker Repos Selection
        id: repos
        shell: pwsh
        run: |
          $repos='${{ secrets.DOCKER_HUB_MINVER_CLI_REPOS }}'.Trim()
          if ($Env:GITHUB_REF_NAME -match '^minver-(\d+\.\d+(\.\d+)?(-.+)?)$') {
            $repos+='%0A'
            $repos+='teslaconsulting/minver-cli'
          }
          if ($Env:GITHUB_REF_NAME -eq 'dev4') {
            $repos+='%0A'
            $repos+='thoho/minver-cli-test'
          }
          Write-Output "content=$repos" >> $env:GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.repos.outputs.content }}
          tags: |
            type=match,enable=true,priority=900,prefix=,suffix=,pattern=^minver-(\d+\.\d+(\.\d+)?(-.+)?)$,group=1
            type=ref,enable=true,priority=600,event=branch
            type=sha,enable=true,priority=500,prefix=sha-,suffix=,format=short

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./minver
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
